tasks:
  - before: |
      pip install -r ./requirements.txt
    command: |
      make docker-up
      make docker-start

vscode:
  extensions:
    - editorconfig.editorconfig
    - ms-python.python
    - voorjaar.windicss-intellisense
    - esbenp.prettier-vscode

ports:
  - port: 5000
    onOpen: notify
