tasks:
  - before: |
      pip install -r ./requirements.txt
    command: |
      docker-compose up -d
      make start

vscode:
  extensions:
    - editorconfig.editorconfig
    - ms-python.python

ports:
  - port: 5000
    onOpen: notify
