tasks:
  - before: make docker-up
    command: make docker-start
  - before: make docker-up
    command: make docker-start-frontend

vscode:
  extensions:
    - editorconfig.editorconfig
    - ms-python.python
    - voorjaar.windicss-intellisense
    - esbenp.prettier-vscode

ports:
  - port: 5000
    onOpen: notify
