tasks:
  - before: |
      pip install -r ./requirements.txt
    command: |
      make docker-up
      make start

vscode:
  extensions:
    - editorconfig.editorconfig
    - ms-python.python

ports:
  - port: 5000
    onOpen: notify
